### PR TITLE
Cleaned up API and aligned some code to Origen conventions

### PR DESCRIPTION
**Pull request by ginty**
@rlaj, please review...

The SWD API was a bit different in how it handled address and data arguments compared to the JTAG driver. This update makes them more comparable.

The old API remains fully supported and all existing tests pass.

Also improved some of the in-line pattern comments, and generally brought the dev environment up to date with latest Origen conventions.

Here is the new API:

``` ruby
# Registers objects can be supplied to provide the address and data values.
# The register bits can be pre-marked for read, store or overlay and which
# will result in the requested action being applied to the cycles corresponding
# to those bits only (don't care cycles will be generated for the others).
dut.swd.write_dp(reg_object)    
dut.swd.read_dp(reg_object)    
dut.swd.write_ap(reg_object)    
dut.swd.read_ap(reg_object)    

# Alternatively, dumb data values can be supplied.
dut.swd.write_dp(0x55, address: 10)
dut.swd.read_dp(0x55, address: 10)    
dut.swd.write_ap(0x55, address: 10)    
dut.swd.read_ap(0x55, address: 10)    

# In the case of read, the data value can be omitted completely, in which case
# it will generate a read operation with don't care on all shift out vectors
dut.swd.read_dp(address: 10)    
dut.swd.read_ap(address: 10)  
```

### CODE REVIEW

**Comment by ginty** [comment]
@rlaj I was wondering why the driver does not actively strobe on the acknowledge handshake, did you have issues with doing that?

**Comment by chrisnappi** [comment]
I don’t think we have ever tried it.  Only one device is using SWD for anything more than mode entry.

**Comment by ginty** [comment]
OK, I have enabled handshake checking now, I think it really should be doing that.

**Comment by rlaj** [comment]
@ginty Looks good.

**Review by rlaj — APPROVED** [review]

**Comment by rlaj** [comment]
@ginty do you think we're ready to merge and release this one?

**Comment by ginty** [comment]
Sorry @rlaj, missed your approval of this

**Pull request merged**
